package GuestRoom;

import java.util.Scanner;

public class 실험2 {

	public static void main(String[] args) {

		
		
		Scanner sc =new Scanner(System.in);
		System.out.println("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKK0000000KKKXXXXNNWWWWWWNNNNNXXXXXXXXNNNNNNNNNNNNNNNXXXXXXXKKKK0OOkkkkkkkxxxxxxxxxxxxxxxdddddddxxdddk0KXKXXXKKKKKKKKK00000000OOOOkkkkkkkkxxddolllcccccccllcccccccloxkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0000KKKKKXKKXXXXXXXXXX\r\n"
				+ "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKK00000KKKKXXXXXXXNNWWWNWNNNNNXXXXXXXXNNNNNNNNNNNNNNNXXXXXXXKKKK00Okkkkkkkxxxxxxxxxxxxdddddddddddddddk0KXXXXXXKKKKKK000OOOOOOkkkxxddddddddooollccccccccccllcccccccldkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000OOOOOOOOOOOOOOOOOOOOOOOOOOOOO00000KKKKKKKXXXXXXXX\r\n"
				+ "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKXXXXXXXXXXXXXNNWWNNNNNNXXXXXXXXNNNNNNNNNNNNNNNNNXXXXXXKKKK00OOkkkkkxxxxxxxxddddddddddddddddddddxOKXXXXXXXKKKKK00OOOkkkxxddoolllllllllllcccccccccccccccccccccodkOOOOOOOOOOOOOOOOOOOOOOkkkOOOOOOOOOOOO0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000OOOOOOOOOO0OOOOO00000OOOOO0000000000KK000KKKKKKKK\r\n"
				+ "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKXXXXXXXXXXXXXXXXNNWWNNNNNXXXXXXNNNNNNNNNNNNNNNNNNXXXXXXXKKKK00OOkkkkkxxxxxxxdddddddddddddddddddddxOKXXXXXXXXXKKK000OOOkkxddooooollllooollllllccc:cccccllcccccloxkOOkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOO000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000OOOOOOOO0000000000OOOOOOOO000000000KKKKK0KKK000KK\r\n"
				+ "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKXXXXKKKKKKXXXXXXXXXXNWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXXXKKKK00OOkkkkkxxxxxxxdddddddddddddddddddddxk0XNXXXXXXXKKK000OOOkkkxddoooooooooooooolllccc::cccclllccccloxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOO0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000OO0000000000000000OOOOOOOOOOOOOOOO00KKKKKKK000000\r\n"
				+ "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKK000000KKK00OOOO0KKXXKKKXXNNWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXXXKKK00OOkkkkkkxxxxxxdddddddddddddddddddddddk0XXXXXXXXXXKK00OOkkkxxxddoooooooollllooollccc::cccccccccccloxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOO0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000OOOOOOOO00000000000000000000000OOOOOOOOOO000KKK000OO000\r\n"
				+ "XXXXXXXXXXXXXXXXXXXXXXXXKKXXXXXKKKKKKKKKKKKKKK000OOkkkxkkO0KKKKKKXXNNWWWNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXXXKK00OOOkkkkkkkxxxxxdddddddddddddddddddddddk0XXXXXXXXXKK00OOkkxxxxddoollllolllllllolllccc:::ccccccccccldxkkkOOOkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOO000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000OOOOOOOOOOOOO0000000000000000000000000OOOOOOOOOOO0OOOOO000\r\n"
				+ "XXXXXXXXXXXXXXXXXXXXXXXKKKXXXXXKK00KKKKKKKKKKKKK00000OOOO00KKKKKKKXXNNWWWNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXXKKK0OOOOOOOOOOkkxxxxdddddddddddddddodddddddx0XXXXXKKKKKK00OOOkkxxdddooolllllllllllllllccc:::ccccccccccoxkkkkOOkkkkkkkkOkkkkkkkkkkkkkkkkkOOOOOOOOOOOO000000000000000000000000000000000000000000000000000000000000000000000000000000000000000OOOOOOOOOOOOOOO0000000000000000000000O0OOOOOOOOOOOOOOOOOO000\r\n"
				+ "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKXXXXXXKKXXXXKKKKXXXXKKXXXXNWWWNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXXKK00OOO0OOOO0OOkxxxxddddddddddddddoooodddooxOKXXXXKKKKKK000OOkkxxdddoooolllllcccllllllcc::::cccccccccldkOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOO000000000000000000000000000000000000000000000000000000000000000000000000000000000000OOOOOOOOOOOOOOOOO000000000000000000000OOOO0000OOOOOOOOOOOOOOOO\r\n"
				+ "XXXXXKKKKKKKKKKKXXXXXXXXXXXXXXKXKK000KKXXXXXXXKKKKKXXXXXKKXXXXXXXXXXXNNWWNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXKK00OOO0OOOO0OkkxdddddddddddddddddooooooooodOKXNXXKKKXKKK00OOkxxddddoooollcccccccccccccc::::cccccc::cldkOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOO0000000000000000000OOO00000000000000000000000000000000OOOOO000000000000000000000OOOOOOOOOOOOOOOOOOOOOO0000000000000000OOO00000000OOOOOOOOOOOOOOO\r\n"
				+ "XXXXXKK0KKKKKKKXXXXXXXXXXXXXXKKKK0OOOO0KKKKKKKKKKKKKKKKKKKKXXXXXXXXXXXNWWNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXKKK0OO00OOOO0OOkxdddddddddddddddddooooooooodkKXXXXXKXXXK000Okxxddoooooollccccccccccccccc:::::ccccc::clxkOkOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOO00000000000000OOO000000000000000000000000000OOOOOOO00000000000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO000000000OOOOOOOOOOO000OOOOOOOOOOOOOOOO\r\n"
				+ "XXXXXXXKXXXXXXXXXXXXXXXXXXXXKKK00OkkkOO00KKKKKKKKKKKKKKKKKKKKKXXXXKKXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXKKK0000000O00OOkxxddddddddddddddddooooooooodx0XXXXXXXXKK00Okxxdddooooollccccccccccccccc:::::::cccc::coxkOkkOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOO0000000000000000000000000000000000000000000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0000000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\r\n"
				+ "XXKKKKKKKKKKKXXXXXXXXXXXXXXXXKK000OO000KKKKKKKKKKKKXXXXXKKKKKKXXXXKKKXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXKKKK00000000OOkkxdddddddddddddddddooooooooooxOKXXXXXKKK00OOkxddddooooollccccccccccccc::::::::::cc:::coxkOkkOOkkkkkkkkkkkxxxkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOO0000000000000000000000OOO0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\r\n"
				+ "XXXXKKKKKKKKKKKKKKKKXXXXXXXXXXXKKKKKKKXXXXXXXXXKKKKXXXXXXXKKKKXXXKKKKXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXKKKKKKKKK00OOkxxdddddddoooooddddddoooooooooodOKXXXXKKKK00OOkxdddooooollccc:::::::::::::::::::::cc:::ldkOOOOkkkkkkkkkkkkkxxxxxkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOO000000000OO00000000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\r\n"
				+ "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKXXXXXXXXXXXKKKXXKXXNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXXKKKKKKKXKK00OOxxddddoooooooooddddooooooooooodkKXXXXKKKK00Okxxxdddoolllccc::::::::::::::::;;;;::c::cloxkOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\r\n"
				+ "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKXXXXXXXXKKKXXXXNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXKKKKKKKKKXXXKK0Okdddooooooooooooooooooooooooloox0XXXXKKK00Okkxxxxddoollccc::::::::::::::::;;;;;::::cloxkOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\r\n"
				+ "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKXXXXXXKKKKKXXNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXKKKKKKKKKKXXXXK0OkddoooooooooooooooooooooooooooodOKXXXXKK00Okxxxxxxdolcccc:::::::::::::::::;;;;;::::coxkOkkOOkkkkkkkkkkkkkkkkkkkkkkxxxxxxxxxxxxxxxxkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\r\n"
				+ "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKXXXXKKKKKKXXNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXKKKKKKXXKKXXKKK0OxddoooooooooooooooooooooooooooodOKXXXXKK00Okkxxxxxdolccc:::::::::::::::::::;;;;:::clxkOOkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxxxxxxxxxxxxxxxkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\r\n"
				+ "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKXXXKKKKKKXXNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXKKKKKXXXXXKKK000OxddoodooooooooooooooooooooooooodkKXXXXKK00OOkxxxxxdolcccc::::::::::::::::;:;;;;;::coxkOkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\r\n"
				+ "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKXXKKKKKKXXNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXXKKK0OOkkxdddddoooooooooooddddooooooddoodk0XXXXKK00OOkxxxxdolcccccc::::::::::::::;;;;;;;;::coxkkkkkkkkkkkkkkkkkkkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\r\n"
				+ "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKXXKKKKKKXXNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXXXXXKKK00OOkxddddoooooooooooooooooooooooooooodkKXXXXKK00Okxxxxdoolccccccc::::::::::;;;;;;;;;;;;;:ldxkkkkkkkkkkkkkkkkkkkkxxxxxxxkkxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\r\n"
				+ "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKXXKKKKXXXXXKKKKKKKKKKKKKKKKKKKKKKKKKXXNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXXXXKKK0OkkxdddooooooolllllllllllloooooooooooooxOXXXXXXK00Okkxxxdollccccccc:::::::::;;;;;;;;;;;;;;:ldxkkkkkkkkkkkkkkkkkkkkkkxxxxkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\r\n"
				+ "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXXKK00OOOkxxddoooodoooooooollllllllloooooollollox0XNXXXXK00Okkxxddlccccccccc::::::::;;;;;;;;;;;;;;;:cdxkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkOOOOOOkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\r\n"
				+ "XXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXNNNNNNNNNNNNNNNNNNNNNNNXXXXXXXKK00OOOOOOkkkkkxxxddoooooooooooooooooooooooooook0XXXXXKKK0OOkxdoolcccccccc:::::::::;;;;;;;;;;;;;;;;coxkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\r\n"
				+ "XXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXNNNNNNNNNNNNNNNNNNNNNNXXXXXXXKKKKKKKK00000OOkkkxxddddddooooooooooooooooooooox0XXXXXKKK00Okxdollcccccccc:::::::;;;;;;;;;;;;;;;;;;:ldkkkkkkkkkkkkkkkkkkxkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\r\n"
				+ "XXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXKKKKK000000OOOkkkkkxxdddddooooooooooooooox0KXXXXKKK00Okxxdolcccccccc:::::::;;;;;;;;;;;;;;;;;;:ldkkkkkkkkkkkkkkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\r\n"
				+ "XXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKK000000000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXNNNNNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXXXXXKKKKK00OOkxxxxxxddddddddoooooooooodddxOKXXXKKKK00Okkxddolccccccc:::::::;;;;;;;;;;;;;;;;;;:ldkkkkkkkkkkkkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\r\n"
				+ "XXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKK0000OOOO0000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKXNNNNNNNNNNWWNNNNNNNNNNNNNNNNXXXXXXXXXKK0000OOkxddooooooolllllllllllllllllooodxOKKKKK0000Okkxxdoolccccc::::::::::;;;;;;;;;;;;;;;:coxkkkkkkkkkkkkkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdddddddddxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkxxkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\r\n"
				+ "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKK00000000000KKKKKKKKKKKKKKKKKKKKKK00KKKXXNNNNNNNNNNNNNNNNNNNWNNNXXXKKKKKKKKKKK00OOO00Okxdooloooolllllllllllllllccllllok0KKKK0000Okkxxxdoollcc:::::::::;;;;;;;;;;;;;;;;;:ldxkkxkkkkkkkkkkkkkxxxxkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxddddddxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\r\n"
				+ "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKK0KKKKKKKKKKKKKKKKKKKKKKKKKKK0000KKKXNNNWWWNNNNNNNNNNNNNNXXXXKKK0000KKKKKKKK000000OkxdoooodooollllllllllllllllllllxOKKKK0000OOkkxxxdoooolcc::::::;;;;;;;;;;;;;;;;::coxkkkxkkkkkkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdddddddxxxxxxxxxxxxxxkxxxkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\r\n"
				+ "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKK0000000000KKKKKKKKKKKKKKK000000KKKXXNNWWWWWWWWWNNNXXXXXXXXXXXXKXXXKKKKKXKKKKKKK00Okkxxxxxxxddooooooooooooollllllok0KKK0000OOkkkxddoooollc::::::;;;;;;;;;;;;;;;;ccldkkkkkkkkxkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdddddddxxxxxxxxxxxkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\r\n"
				+ "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKK0000OOOOO00000000KKKKKKKKKKKKK0000KKKKKKXNNWWNNNNNNNNNXXXXXXNNNNXXXKKKXKKXXXXKK0000OkkxddddooooooooooooooooooooooolooxOKK000000Okkxddollllllc::;;;;;;;;;;;;;;;;;;;:cloxkkxxkkkxxxkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdddddddddddddxxxxxxxxxxxxkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\r\n"
				+ "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKK0000OOOOOOOOOOOOO00000000000KKKK000K00KKKKXNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXK000OkxddddooddoooooolllllllllcccccclllooooooxOKKKKKK00Okkxdolcccccc:::;;;;;;;;;;;;;;;;;;::cloxkkxxkkkxxxkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdddddddddddddddxxxxxxxxxxxkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\r\n"
				+ "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKK00000000OOOOOOOOOOOOOOOOOOO00000000000KKKXXNNNNNNNNNNNNNNNNNXXXXXKK0Okkxddooolllooddxkkkkxxxxxddddoolllcc:;;;;:::ccldk0KKKK00Okxxdoolc::cccc:::::;;;;;;;;;;;;;;::::cooxkkkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxddddddddddddddddddddxxxxxxxxxxkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\r\n"
				+ "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKK0000000000OOOOOOOOOkkkkOO000000000KKKKKXNNNNNNNNNNNNNXXXKK0OOkxdoolllllllooodxkO0KKKKK0O0000OOOkxdooolc:;,,;:cldkOKXXXKK00Okxdooollllollc::::;;;;;;;;;;;;;;;:::clodxkkkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxddddddddddddddddddddddddddxxxxxxxxxxxkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOO\r\n"
				+ "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKK00000000000000000000000000000000000KXNNNNNNNNXK0OOkkxxddddoooooooooooodxkO0KXNNNNNXKKKKK0OOkkkddddoc:;;cldk0KXXXXKKKK00OOkxddooodoolc:;;;;;;;;;;;;;;;:;;::::coddxkkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxddddddddddddddddddddddddddddddxxxxxdxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOO\r\n"
				+ "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKK0000000OOOOOOOOO00000000000KKKK0000KKXNNNXX0kxooloooooddxxxdddddxxxxxkO0KXNNWWWWNNXXKKK0OkkkxxddddooloxkO0KXXXXXXXXXXKKK0OOkkxdooolcc::;::;;;;;;;;;;;;:::;;:codxxxxxkxxxxxxxxxxxxxxxxxxxxxxxdddddddddddddddddddddddddddddddddddddddddxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOkOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk\r\n"
				+ "XXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKK00000000OOOOkkkkkOOOOO0000000000KKK00KXXNXKkdocccclloddxxkkkkkkkkkkOO0KXNNWWWWWWWNNNNXKKKOkkkkkxxxddodx0KXXXXXXKKKK000000OOkkkxdoooooolccccc::::::;;;,,,;;;;;:codxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdddddddddddddddddddddddddddddddddddddddxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOkkOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk\r\n"
				+ "XXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKK000000000000OOOOOkkkkOO00000000KKKKKKXXXKkdlcclllodxkO000K0000KKKXXNNWWWWWWWWWWWNNNNXXKKOkkkkkxxkxxddxOXXXXXNXXXXK00OOOOxdooooc::cclcc:;;;;;;;,,;,,,,,,,;;;:codxxxxxxxxxxxxxxxxxxxxxxddddddddxxdddddddddddddddddddddddddddddddddddxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk\r\n"
				+ "XXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKK0000KKKKKK000OOkkxxkOO0000KK00KKKK0KKKK0Okxdddodxk0KXXNNNNNXNNNNNWWWWWWWWWWWWWWWWNNNXXKOkkkxxxxkkkxdxOXNNNNNNNXXXK00000kdolllc:;;:::;,,,,,,,,,,,;;;,,,,;;:lodxxxxxxxxxxxxxxxxxxxxxxddddddddddddddddddddddddddddddddddddddddddddxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOkk\r\n"
				+ "XXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKKKKK0000000000OOkkxxdxxkOOO00000000000KKKK0000OOOOOO0XNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNX0kxxxxxkkkkkkxkOXWWWNNNNNXXKKKKK0kdolllc:;;:;;,;;;;;,,,,;;;;;;;;:clodxxxkkkxxxxxxxxxxxxxxxxxxxddddddddddddddddddddddddddddddddddxddxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk\r\n"
				+ "XXXXXXXXXXXXXXXXXXXKKKKKKKKKKK00KKKKK000000000OOO0000OOOOOOOOO00000000K00000KKKKK0000000000KNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNKOxxxxxkkkkkkkxk0XWMWWWWWNNXXKKK0Okxxddol::::;;;;;;;;;;;;;::::cloddxkkkkkkkkkkkkkkkxxxxxxxxxxxxxddddddddddddddddddddddddddddddddxxxxxxxxxxkkkkkkkkkkkkkkkkOkkkkkkkkOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk\r\n"
				+ "XXXXXXXXKKKKKKKKKKKKKKKKKKKKKKK0KKKKK000000000000000000KKKKK000OOO00KKKK00000KKK00000000000KXNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNX0kxdxxxkkkxxxxxkOXWMMMMMWWWNNXK0Odlllllc::::::::::;;;;;;;:::ccodkkkkkxxxkkkkkkkkkkkkkxxxxxxxxxxxxddddddddddddddddddddddddddxdddddxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk\r\n"
				+ "XXXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK000000KK0000OO000KKKKKK0000000KKKK0000000000000000000KXNWWWWWWWWWWWWWMMMMMWWWWWWWWWWWWNNXK0kkkxxkkkkkkxxxkKNWMMMMWWWNNNNX0xlclllcccc::::::::::;;;;::::cldxkkkkkkkkkkkkkkkkkkxxxxxxxxxxxxxxxxdddxdddddddddddddddddddddddddddxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk\r\n"
				+ "XXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK00000000OOOOO0000000KKKK000OOOOOO000000000000000000KXNNWWWWWWWWWWWWMMMMMWWWWWWWWWWWWNWNNK00Okxkkkkkkkxxk0XWMMMMWWWWNNNXKkoooooolllccccllcccc:::::ccclodxkkkkkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxddddddddddddddddoodddoodddddddddddddxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxdddddxxk\r\n"
				+ "KKKKKKKKKKKKKKKKKKKKKKKKKKKKK00KKKKKKKKK000000000000000KKK000KK0OkxddddxkkkOOO0000000000000KXNNWWWWWWWWWWWWWMMMWWWWWWWWWWNWWNNNXK00OkxxkkkkkkxxkOXWWWWMWWWWWWNX0kddddddollllllllllllllllloooddxxxxxxkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxdddddddddddddddooooooooooooodddddddddddxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxddddddxx\r\n"
				+ "KKKKKKKKKKKKKKKKKKKKKKKKKKKKK00KKKKKKKKK000000KKKK000000K0000000OkkkkkkkOOOOO000000000000O00KXNWWWWWWWWMMMMMWWWWWWWWWWWWWWWWNNNXKK00Okxxkkkkkkxxk0NWWWWWWWWWNNXOkxxxkxxdooolllooooooooooddddddxxxxxxxxxxkkxxxxxxxxxxxxxxxxxxxxxxxdddddddddddddddoooooooolllllllloooodddddddddxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxkk\r\n"
				+ "KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK00000000OOO000000000000000000000000000000000000000000000KXNWWWWWWWWMMMMWWWWWWWWWWWWWWWWWNNNXXKK0OkxxkkkkkkkxxOKNWMWWWWWWWNXOxxxkkkxdddooooooodddddddddxddddxxxxxdxxxkkkkxxxxxxxxxxxxxxxxdddddddddddddddoooooollllllllllllllllloodddxxxxxdddddddddxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk\r\n"
				+ "KKKKKKKKXXXXXKKKKKKKKKKKKKKKK0KKKKK00000000OOOOOOOO000000000000000000000OO0000000000000000O00XNWWWWWMMMMWWWWWWWWWWWWWWWWWWWWNNNXXKK0OkkkkkkkkkkxxxOXWMMWWWWWNNXOxxxkkxxddddooooooddddddddxxxdxxxxxxxdddxxxxxxkkkxxxxxxxxxdddddddddddddddooooooolllloooooooooooooooodddddddxxxddddddoodddxxxxxxxxxxxxxxxkxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk\r\n"
				+ "KK00000KKKKXXKKKKKKKKKKKKKKKK000000000000000000000OOO00000000000000000000000000000000000OOO0KXNWWWMMMMMWWWWWWWWWWWWWWWWWWWWWWNNXKK00Okkkkkkkkkkkxdk0NWMWWWWWNNKOkkkkkxxdodddoooooooddxxxxxddddxxxkxxxddddddxxxxxxxxxxddddddddddddddddddoooollcc::::ccccccccllllllloooooooooooodooooooooddddddddxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk\r\n"
				+ "O000000000KKKKKK000000000000000000000000000000Okkxxxxk0000000000KKKK00000000000000000000OO0KXNWWWWMMMMMWWWWWMWWWWWWWWWWWWWWWWNNXKK000OkkkkkkkkkxxxxkKNWWWWWWNXKOkOOkxxddoodddoooollodddddolllooodxxxxddddddddddodddddddddddddddddddooollllllcc:::::::::::ccccccccc:::::::::ccccc::ccloooooooodddddddddxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk\r\n"
				+ "000000000OOOOkkkkkkkOO00000OO0000000000000000OkxddoodkOOO000000000000000000000000000000000KXNWWWMMMMMMMWWWWWWWWWWWWWWWWWWWNNNNNXK0KK0OkkkkkkkxxxxxxxOXWWWWWNNXK0OOkxxxxdoooooooooooooooolllllllloooddddddddddoolllooooooddddddddddddoolloooooooooollloooollllc::;;;,,,,'',,,;:::::clloollllllloooooddddddddddxxxxxxxxxxxxxxxkkkkkkkkkkkkxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk\r\n"
				+ "XKKKKK000OkkkkkxxxkkOO000000000000KKK000000000OOOkkkkOOO00000000000000000000000000000OO0KXNWWWWMMMMMMWWWWWWWWWWWWWWWWWWWWNNNNNXXK0KKKOkkkxxkkkxxkkxdkKWWWWWWNXK000Oxxxxxddoooooooooooooolloooooooooolllooooooollcclloddddxxxxdddxxdddddddddddddddoooooddoooool::;;;;;;,,'''',;::cllllllllccccccllllooooooooddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxx\r\n"
				+ "KKKK00000OOO000000000000000000000KKKK0000000000K000000000000000000000000000000000000000KXNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNXXK0KKKOkxxxxxxxxxkxxxx0XWWWWWNXK000Oxddxxxddoooooooooooooooooooooooooollllllllllllllloddxddxxxdddxxddddxxdddddddddddoodooodooollcccccc:;,'''',;:ccclcc:::::::cccccccclloolllllooddddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkxxxxkxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxx\r\n"
				+ "000000OOO000KKKK00000000000000O0000000000OO0000000000000000KK000000000000000000000000KKXNWMMMMWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNXXXXK0KKKOkxxxxxxxxxxxxxxOKNWWWWNXK00Okxdoddddddoooooooooooooooooooooooooooooooolllloolcloddddddddddddddddddddddddddddddddoooooooooooolllc:;;;;;:ccllllccc:::::cccccccccccllccc::cclloooooddddddddddddddxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxx\r\n"
				+ "00KKKKK000000000000000OOOOOOOOOOO0000000000000000000000000000000000000000000000000000KNWWMMWMMWWWWWWWWWWWWWWWWWWWWWWNNNNNNNXXXXXKKKKKOkkxxxxxddxxxxxxk0NNNNNNXK00Okxdoooooodddoooooooooooooooooooooooooooooooooooollccodddddddddddddddddddddddddddddooooooooooodooolllllclllllooooooollllllllllllllllllllccccccllllloooooooooddddddddddddxxxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk\r\n"
				+ "KKKKK00OOOkkkkxxkkkkkkkxxkkkkkkOOOOOO00000000000000000000000O00000000000000000000000KNWWMMWWWMWWWWWWWWWWWWWWWWWWWWWNNNNNNNNXXXXXK00K0OxxxxxxxxxxxdddxxOXWWWNNXK00OOkxdoooooooooooooooooooooooooooolllllllllloooollll::loddddddddddddddddddddddddddddddooooooooooooolllllloooooooooooooooooooollllllooolllllllllooooollllloooooooooooooddddddddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkxxxxxxxxxxxxxxxxxxxxxxxxxxkkkkxxxx\r\n"
				+ "KKK0OxddddddddddddddddodddxxxkkkOO00000000000000000000000000OOOOO00OOOO000000000000KXNWMMWWWMMWWWWWWWWWWWWWWWWWWWWNNNNNNNXXXXXXXKKKK0OkxxxdxxxxxdddddxOXNWNNXXK0O0Okxdooooooloooooooooooooooooollllllllllllllllllllc:;cllllllllloooooooooooooooooooooooooooooooooooooooooooooooooooooooolllloooooloooollllllooooolllllllllllllllooooooooooooodddddddddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\r\n"
				+ "00kxddoooddddddddoooooooddxxxxkkOOOOOOOO00000000000000000000000OOOOOOOOOO00O000000KXNWWMWWWWMMWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNWNNNNNXXK0OOkxxxxxddddddxOXNNNXXXK0000Oxddoolllllloooooooooooooollllcccccccccccclccccc:;;:::::::::::cccccccccccccclllllllllllllllllllloolllllollllllllooooooollloooooooolllooooolllllloollllllllllllllllllllooooooooooooddddddddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\r\n"
				+ "OkxddxxxxxxxxxxxxxxkkkkkkkOOOOOOO00000O0000000000000000000000000000OOOOOOOOOO000KXNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNXXXK00OOkkkkxxddddx0NWWNNNNXXXXK0Okxddoolllllllllloooooollllllllllccccc:::::ccc:;;;;;::::::::::::::::::::::::::::::::::::::::::ccccccccccccccccccllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllloooooooooodddddddddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\r\n"
				+ "kkkkkkkOOkkkkkkkOOO000OOOOO000000000000000000000000000000000KKK0000000000OOO0000KNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMWWWWWWWWNNNNNNXXKK00OOkkkkkkkxxddx0NWWWWWWWNNNNXXK0Okkxddddoollloooolllloooooooollllccc::cclllc:;;;;;;;;;;;;:::::::;::;;;;::::::::;;::::::::::::::::::::::::::::::::::::ccccccccccccccccllllllccclllllllllllllllllllllllllllllllloooooooooooooddddddddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\r\n"
				+ "OOOOOOOOOOOOOOOOOOOOOO00OOOOOO0000000000000000000000000000000000000000000000000KXNWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMWWWWWWNNNNNNNNNNNNNXXXK00Okkxkkkkxxxdx0NWWWWWWWWWNNNXXKK0OOkkkxxxddddddddooddddooooolllccccclloolc:;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::;;;:;;::::::::::::::::::::::::::::::::::::::::::::cccccccclllllllllllllllllllllllllllllllllooooooooodddddddddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\r\n"
				+ "0000000000OO000000OOO00000000000O00000000OOO0000000000000000000000000000000000KXNWWWWWWWWWWWWWWWWWWWWWWWWMMMMMWWWWWWWNNNNWWNNNNXXXXKKKK00OOkkkkxxxddddkKNWWWWNNNNNNXXXKK0OOkkkkkkkxkkkxxxxxxdddoooollcccccllcc::;;,,,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:;:::::::::::::::::::::::ccccccccccllllllllllllclllllllllloooooooooodddddddddddxxxxxxxxxxxxxxxxxxxxxxxx\r\n"
				+ "0000000000000000000000000000000000000000000000000000000000000000000000000OOO0KXNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNXXNNNNXXXXXKKK000OOkkkkkkxxxdddxOXWWWWNNNNNNNXXKK00OOkkkkkkkkkxxxxxxddddolcc::;;;;;;;,,''.'',,,,,,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:::::;;:::::::::::cccccclllllcccclllcclllllllllooooooooooddddddddddddddddxxxxxxxxxxxxxx\r\n"
				+ "0000000000000000000000000000000000000000000OOOO000000OOO000000000000000OOOO0KXNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNXXXXXKKKKK000OOOkkkkkkxxxxxdddkKNWWWNNNNNNXXKK00OOkkkkxxxxxxxxdddddddol:;,,''''''...'''''',,,,,,,,,,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:::::::ccccccccclllllllllllllllllllooooooooooddddddddddddddxxxxxxxxxxx\r\n"
				+ "KKK000000KKKKKKKKKKKK0000000KKK00000000000000000000000OOOOOO0000000000OOOO0KXNWWWWWWWWWWWWMWWWWWWWWWWWMMMMWWWWWWWWWNNNXXKKKKXXKKKKKK000OOkkxxxxxxddddddx0XNWWNNNNNXXKK00OOkkkkxxxxxxxxxdddddool:,...'..''''''''',,,,,,,,,,,,,,,,,,,,;;;;;;;;;;;;;,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::::::::::cccccccccllllllllllllllooooooooooddddddddddddddddddddd\r\n"
				+ "00000000000000KKKKKKK00KKKKKKKK0KKKKKK000KKKKKKK000KK00000000000000000OO0KXNWWWWWWWWWWWMMMWMWWWMMMWWMMMMMWWWWWWWNNNNXXXXKKKKKK00OOOkkkkkkkkkkxxxdddoooodk0XXNNNXXXXKK00OOkkkkkkkxxxxxdddooooolc,'..'''',,,,,,,,,,,,,,,,,,,,,,,,;,,,,,;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::::;;;;;;:::::::::cccccccccclllllllloooooooddddddddddddddddddd\r\n"
				+ "00000000000O000000000000KK00000000KK0000000000KKKK00KKKKKK000000KK00OOO0XNWWWWWWWWWWWWWWWWWWWWWWWWWMMMMWWWWWWWNNNNXXXKK00OOkkxxxxdddooooooddddddddddoolodOKNNNNNXNNXKKK0OOkkkxxxxxxxxddoooollc;,''',,,,,,,,,,,,,,,,,,,,,,,;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:::::::::::ccccccllllllloooooooodddddddddddd\r\n"
				+ "K00000000000000000000000000000000000000000000000000000000000000000OOOO0XNWWWWWWWWWWWWMMMMMMMMWWWWWWWWWWWWNNNNNNXXXKK00OOOOOkkkkxxxddooollllllllllllollllokKXXXXXXXXXKK000Okkkxxxxxxdddoollc:;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;;;;;;;;;;;,,,,;;;;;;;;;;;;,,,,,,,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::::::::::::::ccccccclllllllooooooodddddd\r\n"
				+ "00000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK000K00000000000OOOOOOOOOOOO0KXNWWWWWWWWWWWWMMMMMMMMMWWWWWWWWWNNNNNNXXXKK00OOOOOOOOkkxxxxxxxxdddooooollcccc::cccloxO000000OOOOkkxddolllllllllllcc:;;,''',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;;;;;;;;;,,,;,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::::::::::::::::cccccclllllooooooooddd\r\n"
				+ "OOOOOOOO0000000000000000KKKKKKKKKKKKKKKKKKKKKKKK0KK000KK0000OOO00KKKXNWWWWWWWWWWWWWMMMMMMMMMWWWWWWNNNNNNNXXXKK00OOOkkkxxkxxxdddddddddddoooooollcc:::;;:::cclooollllllcccc::;;;,,,,,'''''''''''',,,,;;,,,,,,,,,,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;;;,,,,,,,,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::::::::::::::ccccccllllllloooooooo\r\n"
				+ "kkkxkkkkkkkOOOOOOOOOOOOOOOOO00000000OO00000KKKKKKKK000KKKK000KKXXNNWWWWWWWWWWWWWWWWMMMMMMMMWWWWWWNNNNNNXXK00OOOOkkkkkkkxxxxxxdddddooolllllllllcccc::;;:clllccllllllc:;;,,,,,'''''...''''''',,,,,,,,;;;;,,,,,,,,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;;,,,,,,,,,,,,,,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::::::::::ccccccllllllllllooooo\r\n"
				+ "kxxxxxxxxxxkkkkkkkkkkkxxxxxxkkOOOOOOOkkkOOOOOOOO000OO00000O00KXNWWWWWMMWWWWWWWWWWMMMMMMMMMWWWWWWNNNXXKK00OkkkkOOkkkxxxxddddooooolllcclloolllllccc:::::codxxddxxxddddoolllllcc::::ccccccccc:::cccccc:::::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;,,,,,,,,,,,,,,,,,,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;::::::::::ccccccclllllllllooooo\r\n"
				+ "OOOOOOOkkkkkkOOOOOOkkkkkxxxxxkkOOOOkkxxxxkkxkkOOOOOOkkO0000KXNNWWWWWWMMMWWWWWMMMMMMMMMMWWWWWWWWNNNXXK0Okxdddddddoooooooollllllllllllllloolllcccc::::cloxkkxxxkxxxxddddddddddddoooddddddooooooddddooooooollllllllllllllllcccccccccccccc:::::::::::::;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;;;;;;;;;;;;;;;;;;;;;;::::::::::cccccccclllllllllllll\r\n"
				+ "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkxxddoddxxxxxxxdxkOO0KNWWWWMMMMWWWWWWWWWMMMWWWWWWWWWWWWNNXXK0OOkxddddoooollloooooollllllllllllllllllcccc::::clodxxkxxxxxxxxxdddddddddddddddddddddddddddddddddoooooooooooooooodooooooooooooooooollllllllllllllcc::::cccc:::::::::::::::::;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;;,,;;;;;;;;;;;;;;::::::::cccccccccllllllllllll\r\n"
				+ "OOOOOOOOOOOOOOOOOOO00000OOOOOOO000OOOOOOkkxxxxxxxxxxxdddddkKNWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNXK00Oxxdddooooooooollllollllllllcccccccccccccc::::cloddxxxxxxkxxxxxxxdddddddddddddddddddooooddddoooooddooooooooooooooooooooooooooooooooooooooooolllllllllllllllllllllllllllclllllcccccccccccc::::::::::;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;,,,,,,;;;;;;;;;;;;;;;;;;;;:::::::cccccccclllllllllllll\r\n"
				+ "OOOOOOOO0000000OOOOOOOOOOOO000000OOOOOOOOOOOO000OOOOOkkkxx0XNWMMMWWWWWWWWWWWWWWWWWWNNNNNNNXXK0Okxxddooooolllllllcccccccc:::ccccc:::::::::ccccclodxkkkxxxxxkkxxxxxxddddddddddddddddddddddddddddddodddddoooooddoooooooooooooooooooooooooooooooollllllllllllllllllllllllllcccccccclllllllllllllccclcccccccccccccc:::c::::::::::::;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,;;,,,,;;;;;;;;;;;;;;;:::::::::cccccclllllllllllll\r\n"
				+ "OOOOOO0000000000OOOkkkkkOOOOO000000OOOOOOOOOOOOOOOOOOOOOOOKNNWWWMWWWWWWWWWWWWWWWWNNNNNXXXXKK0Okxdollllllllllllcccccccccc:::::::::::::::cloxxxxxxkkkkxxxxxxxxxxxxddddddddddddddddddooodddddoddddooodddddooodddddoooooooooooooooooooooolllooollllllllllllllllllllllllllllccc:::ccccllllllllllllllllcccccccccccccccccccccccccccccccccccccccccccccc::::::::::::::;;;;;;;;;;;;;;;;;;;;;;;;;:;;;:::cccccccclllllllllll\r\n"
				+ "OOOOOOO000000000000000O000OOOO0000000OOOOOOOOO0000OOOOOOOOKNNNWWWWMWWWWWWWWWWNNNNXXXKKK00OOkkxddollccccccc::c:::::;::::::::::::;::::::cclodxxxddddddddddddddddddddddddddddddddddddddddddoooooooooooooooooooodddddooooooooooooooolloollllloolllllllllllllllllllllllllllllllcccclllllllllllllllcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc::::::::::c:::::::::::::::ccccccccclllllllllooo\r\n"
				+ "OOOOOOOOOO000OOOOO0000000000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOKNNWWWWWWWWWMWWWNNNNXXK000OOkxxdoolllcccccc::::::::::::;;;:::::cc:::cc:::::::ccllllllllllllllllllllllllllllllllllllllllllllllllloooooooooooooooooooodddooooooooooooooollloollllloolllllllllllllllllllllccccccccccccccllllccccclllllllcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc:cccccccccccccccccccclllllllllloooooooooo\r\n"
				+ "OOOOOOOOOOOOOOOOOO00000000OOOOOOOOOOOOOOOOOOOOOOOOOOOO00OOKNWWWWWWWWWWWWNNXNNXK0Okxxddoollccccccccc:::::::::::::::::::cccccccllllc:::::ccc:::ccccccccc:::::::::::::::::::::::::::::::::::::cccccccclllllllooooooodddooooooooddoooooooollllllllllllllooolllllllc::::::::::ccccccllllllllllllllllllccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccllllllllllllllooooooooooooo\r\n"
				+ "OOOOOOOOOOOO0000000OOOOOOOOOkkOOOOOOOOOOOOOOOOOOOOOOO000OOKNWWWWWWWWNNNNXXKK0Okxddoolllccccccccc:::::::::::::::::::;;:::cc:::ccllllc::::::::::::::::::::::::::::::::;;;:::::::::::::::::::;;;;;;;::::::::ccccllloooooooddoooddooooooooolllllllllloooooollllllcc:::::cc:::cccccccclllllllccclllllllllccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc::::cccccccccclccccccllllllcllllllooooooooooooo\r\n"
				+ "OOOOOOOOOOOO0000000OOOOOOOOOOOOOOOOOOOO00000OOOO0000000OOOKXNWWWWWWNXKK00OOkxdooooooollcccccccc:::::::::::;:::;;;;;;;;;;;:::::::cccc:;;:::::::::::::::::::::::;;;;;;;;;:::::;;;;;;:::::;;;;;;;;;;;;;;;;;;;;:::::ccccccccllllllllloooolllllllllllllllllllllolllcc:::::ccllccccc:::ccccccccccllllllllllccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc:::::ccccccccccccccccclllccllllllloooooooooooo\r\n"
				+ "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO00000000000OOOOOkkkO0XXNXXXKOkkxxdddoollooooollcccccc::::::::;;;;;;;;;;,,,,,,,,,,;;;;;;;:::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::;;:::::::::::ccccccccccclllcccccllllccc::;;;:cclcc:::::::;;;:::ccccccccllllcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccllccccccllllllllooooooooooo\r\n"
				+ "OkkkkkkOOOOOOOOOOOOOOOOOO000OOOOOOOOOOO00000000000OOOOOOkkxdxxkkkkkxdooollllllclllcccccc:::::::;;;;;;,,,;;,,',,,,''''''',,,',,,,,,,,,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::::::cccc::;;;;;::ccccc:::ccccc::::::cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccclllccccccllllllllloooooooooo\r\n"
				+ "OkkkkOOOOOOOOOkkOOOOOOOOOOOOOOOOOOOOOO000000OOOOOOOOOOOOkkxxdollclooolccccccccccc::::::::;;;;;;,,,,,,,'''''''''...............''..'',,,,,,,,,,,,,,,,,,,,,;;;;;;;,,,;;;;;;;;;;;;;;;;;;;;;;;;;,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,''''',,,,,''''''.....'''''',,,,,,,,;;;:::;;;:::::::ccccc:cccccccccccccllcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccclcccccccllllllllloooooooooo\r\n"
				+ "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkxxddoollloooooooollccccc:::;;;;;;;,,,,'''''............................'''',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;,,;;;;;;;,,;;;;;;;;;,,,,,,,;;,,,;,,,,,;;;;;;;;;;;;;,,''..........................''''''''''',,,'',,,,,,,,,;;;;;;;;;;;;;;;:::::::::cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccclllllllllloooooooo\r\n"
				+ "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkxxxxxxdddddddxxdddddxddooollllllcccccc::;;,,,,,'''''''''''''''''''''''',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;,,,,,''''''.....''''''''''''''''''''''..........'''''',,''',,,,,'''''''',,,;;;;;;;;;;;;:::::;::::::::::cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccllllllllllllooooo\r\n"
				+ "OOOOOOOOOOOOOOkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkOOOOkkkkkkkkkxxxxxxxxxxxxkxxxxxddxxxddxxxxdddoollccccccccccllllcccccc:::::;;::::;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,'''''''''''''.......'''',,,,,,,,,,,,,,,,,,,,,,,,,,,;;;;;;;;,,,,;;;;;;;;;;;;;;;;;;;:::::::::::::cccccccccccccccccccccccccccccccccccccccccccclllllllllllloooo\r\n"
				+ "kkkkOOOkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkOkkkkkkOOOOOOOOOOOkkkkkkkkxxxxkkxxddxxxxxxddxxxkxxxxddooooooooooooooooooooollllolllloolllllllolllcclcccc::::::::::;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,''''....'''''''''''''''''',,,'''''''''''''''''''''''',,,,,,''''',,,,,,,,,,;;;;;;;;;;;;;;;;;:::::::::::::::::ccccccccccccccccccccccccclllllllllll\r\n"
				+ "kkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOkkkkkkkkkkkkkkkxxddxxxdddddddxxxxxxdddoooodddooooooooooooooooooolllooooooodddooolloooooolloooollllllllllcccccccc::::::::;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,',,,,'''.........................................''....'''''''',,,'''',,,,',,,,,,,,,,,,;;;,;;;;;;;;;;;;;;;;;;::::::::::ccc::cccccccccllllll\r\n"
				+ "kkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOkkkkkkkkkkkkkkkxxxxxxxxdddddddddxxxxdddddddooodddddddoooooddoooolloooooooooooooooooooolllloooooolllloollllllllllllllllllllccccccccc::::::::;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,'''........................'''.''''''''''''''''''''''''''''''''.........'',,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;;;;;;;;;;:::::::::::::cccccc\r\n"
				+ "kkkkkkkkkkkkkkkkkkOOOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxxdddddddddddddddddddooooodddddddddddddddddooooddoooooooooooooooooooooooooollllllllllooollllllllllllllllllllllllllllllcccccc:::::::;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,'''''''");
		
		
		
		
		
		
		
		
	}

}
